server:
  port: 22200

spring:
  application:
    name: storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.117:8848
        namespace: public
        enabled: false
        register-enabled: false
    sentinel:
      transport:
        dashboard: 192.168.1.117:8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.117:3306/flash_sale?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.vinci.flashsale.storage.biz.entity
  configuration:
    map-underscore-to-camel-case: true

dubbo:
  application:
    name: storage-api-service
    qos-port: 22210
  registry:
    address: nacos://192.168.1.117:8848
  protocol:
    name: tri
    port: 22220
    host: 192.168.1.117
    serialization: protobuf
  scan:
    base-packages: com.vinci.flashsale.storage.biz.api
  consumer:
    check: false
    timeout: 5000
  provider:
    timeout: 5000
    group: DUBBO_GROUP
    version: 1.0.0